### ISSUE TITLE
Write Pydantic schemas

### ISSUE THREAD

**Issue by vshekar** [NSLS2/recap#1]
## Issue

Complex experimental data should be expressed in a declarative manner such that it is easy for a user to interact with the system. If a scientist wants to define an experiment they can do so using a yaml file like so:

```yaml
experiment_template:
  name: PCR
  actions:
    - name: Heat
      parameters:
        - name: Temperature
          type: float
```

A pydantic schema can validate such a yaml file OR data coming in from an API.
